package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private int id;
     private String Street;
     private String StreetNo;
     private String City;
     private String County;
     private String Country;
     private String ZipCode;
     private String Notes;
     private boolean IsPrimary;
     private int persondata;
     private PersonData m_PersonData;

    public Address() {
    }

    public Address(String Street, String StreetNo, String City, String County, String Country, String ZipCode, String Notes, boolean IsPrimary, int persondata, PersonData m_PersonData) {
       this.Street = Street;
       this.StreetNo = StreetNo;
       this.City = City;
       this.County = County;
       this.Country = Country;
       this.ZipCode = ZipCode;
       this.Notes = Notes;
       this.IsPrimary = IsPrimary;
       this.persondata = persondata;
       this.m_PersonData = m_PersonData;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getStreet() {
        return this.Street;
    }
    
    public void setStreet(String Street) {
        this.Street = Street;
    }
    public String getStreetNo() {
        return this.StreetNo;
    }
    
    public void setStreetNo(String StreetNo) {
        this.StreetNo = StreetNo;
    }
    public String getCity() {
        return this.City;
    }
    
    public void setCity(String City) {
        this.City = City;
    }
    public String getCounty() {
        return this.County;
    }
    
    public void setCounty(String County) {
        this.County = County;
    }
    public String getCountry() {
        return this.Country;
    }
    
    public void setCountry(String Country) {
        this.Country = Country;
    }
    public String getZipCode() {
        return this.ZipCode;
    }
    
    public void setZipCode(String ZipCode) {
        this.ZipCode = ZipCode;
    }
    public String getNotes() {
        return this.Notes;
    }
    
    public void setNotes(String Notes) {
        this.Notes = Notes;
    }
    public boolean isIsPrimary() {
        return this.IsPrimary;
    }
    
    public void setIsPrimary(boolean IsPrimary) {
        this.IsPrimary = IsPrimary;
    }
    public int getPersondata() {
        return this.persondata;
    }
    
    public void setPersondata(int persondata) {
        this.persondata = persondata;
    }
    public PersonData getM_PersonData() {
        return this.m_PersonData;
    }
    
    public void setM_PersonData(PersonData m_PersonData) {
        this.m_PersonData = m_PersonData;
    }




}


