package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA



/**
 * Communication generated by hbm2java
 */
public class Communication  implements java.io.Serializable {


     private int id;
     private String Type;
     private String Value;
     private String Notes;
     private boolean IsPrimary;
     private int persondata;
     private PersonData m_PersonData;

    public Communication() {
    }

    public Communication(String Type, String Value, String Notes, boolean IsPrimary, int persondata, PersonData m_PersonData) {
       this.Type = Type;
       this.Value = Value;
       this.Notes = Notes;
       this.IsPrimary = IsPrimary;
       this.persondata = persondata;
       this.m_PersonData = m_PersonData;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.Type;
    }
    
    public void setType(String Type) {
        this.Type = Type;
    }
    public String getValue() {
        return this.Value;
    }
    
    public void setValue(String Value) {
        this.Value = Value;
    }
    public String getNotes() {
        return this.Notes;
    }
    
    public void setNotes(String Notes) {
        this.Notes = Notes;
    }
    public boolean isIsPrimary() {
        return this.IsPrimary;
    }
    
    public void setIsPrimary(boolean IsPrimary) {
        this.IsPrimary = IsPrimary;
    }
    public int getPersondata() {
        return this.persondata;
    }
    
    public void setPersondata(int persondata) {
        this.persondata = persondata;
    }
    public PersonData getM_PersonData() {
        return this.m_PersonData;
    }
    
    public void setM_PersonData(PersonData m_PersonData) {
        this.m_PersonData = m_PersonData;
    }




}


