package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MaritalStatusT generated by hbm2java
 */
public class MaritalStatusT  implements java.io.Serializable {


     private int id;
     private int Code;
     private String Description;
     private Set SocioDemographicDatas = new HashSet(0);

    public MaritalStatusT() {
    }

    public MaritalStatusT(int Code, String Description, Set SocioDemographicDatas) {
       this.Code = Code;
       this.Description = Description;
       this.SocioDemographicDatas = SocioDemographicDatas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCode() {
        return this.Code;
    }
    
    public void setCode(int Code) {
        this.Code = Code;
    }
    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }
    public Set getSocioDemographicDatas() {
        return this.SocioDemographicDatas;
    }
    
    public void setSocioDemographicDatas(Set SocioDemographicDatas) {
        this.SocioDemographicDatas = SocioDemographicDatas;
    }




}


