package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA



/**
 * PatientCarer generated by hbm2java
 */
public class PatientCarer  implements java.io.Serializable {


     private int id;
     private int patient;
     private int carer;
     private boolean isprimary;
     private Patient m_Patient;
     private Carer m_Carer;

    public PatientCarer() {
    }

    public PatientCarer(int patient, int carer, boolean isprimary, Patient m_Patient, Carer m_Carer) {
       this.patient = patient;
       this.carer = carer;
       this.isprimary = isprimary;
       this.m_Patient = m_Patient;
       this.m_Carer = m_Carer;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPatient() {
        return this.patient;
    }
    
    public void setPatient(int patient) {
        this.patient = patient;
    }
    public int getCarer() {
        return this.carer;
    }
    
    public void setCarer(int carer) {
        this.carer = carer;
    }
    public boolean isIsprimary() {
        return this.isprimary;
    }
    
    public void setIsprimary(boolean isprimary) {
        this.isprimary = isprimary;
    }
    public Patient getM_Patient() {
        return this.m_Patient;
    }
    
    public void setM_Patient(Patient m_Patient) {
        this.m_Patient = m_Patient;
    }
    public Carer getM_Carer() {
        return this.m_Carer;
    }
    
    public void setM_Carer(Carer m_Carer) {
        this.m_Carer = m_Carer;
    }




}


