package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * QuestionnaireQuestion generated by hbm2java
 */
public class QuestionnaireQuestion  implements java.io.Serializable {


     private int id;
     private String type;
     private boolean isPrimary;
     private boolean subquetsions;
     private int parentid;
     private String title;
     private int quest;
     private QuestionnaireQuestion m_QuestionnaireQuestion;
     private Questionnaire m_Questionnaire;
     private Set QuestionnaireQuestionAnswers = new HashSet(0);
     private Set QuestionnaireAnswers = new HashSet(0);

    public QuestionnaireQuestion() {
    }

    public QuestionnaireQuestion(String type, boolean isPrimary, boolean subquetsions, int parentid, String title, int quest, QuestionnaireQuestion m_QuestionnaireQuestion, Questionnaire m_Questionnaire, Set QuestionnaireQuestionAnswers, Set QuestionnaireAnswers) {
       this.type = type;
       this.isPrimary = isPrimary;
       this.subquetsions = subquetsions;
       this.parentid = parentid;
       this.title = title;
       this.quest = quest;
       this.m_QuestionnaireQuestion = m_QuestionnaireQuestion;
       this.m_Questionnaire = m_Questionnaire;
       this.QuestionnaireQuestionAnswers = QuestionnaireQuestionAnswers;
       this.QuestionnaireAnswers = QuestionnaireAnswers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public boolean isIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(boolean isPrimary) {
        this.isPrimary = isPrimary;
    }
    public boolean isSubquetsions() {
        return this.subquetsions;
    }
    
    public void setSubquetsions(boolean subquetsions) {
        this.subquetsions = subquetsions;
    }
    public int getParentid() {
        return this.parentid;
    }
    
    public void setParentid(int parentid) {
        this.parentid = parentid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public int getQuest() {
        return this.quest;
    }
    
    public void setQuest(int quest) {
        this.quest = quest;
    }
    public QuestionnaireQuestion getM_QuestionnaireQuestion() {
        return this.m_QuestionnaireQuestion;
    }
    
    public void setM_QuestionnaireQuestion(QuestionnaireQuestion m_QuestionnaireQuestion) {
        this.m_QuestionnaireQuestion = m_QuestionnaireQuestion;
    }
    public Questionnaire getM_Questionnaire() {
        return this.m_Questionnaire;
    }
    
    public void setM_Questionnaire(Questionnaire m_Questionnaire) {
        this.m_Questionnaire = m_Questionnaire;
    }
    public Set getQuestionnaireQuestionAnswers() {
        return this.QuestionnaireQuestionAnswers;
    }
    
    public void setQuestionnaireQuestionAnswers(Set QuestionnaireQuestionAnswers) {
        this.QuestionnaireQuestionAnswers = QuestionnaireQuestionAnswers;
    }
    public Set getQuestionnaireAnswers() {
        return this.QuestionnaireAnswers;
    }
    
    public void setQuestionnaireAnswers(Set QuestionnaireAnswers) {
        this.QuestionnaireAnswers = QuestionnaireAnswers;
    }




}


