package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Questionnaire generated by hbm2java
 */
public class Questionnaire  implements java.io.Serializable {


     private int id;
     private BigDecimal version;
     private Set QuestionnaireQuestions = new HashSet(0);
     private Set Tasks = new HashSet(0);

    public Questionnaire() {
    }

    public Questionnaire(BigDecimal version, Set QuestionnaireQuestions, Set Tasks) {
       this.version = version;
       this.QuestionnaireQuestions = QuestionnaireQuestions;
       this.Tasks = Tasks;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BigDecimal getVersion() {
        return this.version;
    }
    
    public void setVersion(BigDecimal version) {
        this.version = version;
    }
    public Set getQuestionnaireQuestions() {
        return this.QuestionnaireQuestions;
    }
    
    public void setQuestionnaireQuestions(Set QuestionnaireQuestions) {
        this.QuestionnaireQuestions = QuestionnaireQuestions;
    }
    public Set getTasks() {
        return this.Tasks;
    }
    
    public void setTasks(Set Tasks) {
        this.Tasks = Tasks;
    }




}


