package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA



/**
 * QuestionnaireQuestionAnswer generated by hbm2java
 */
public class QuestionnaireQuestionAnswer  implements java.io.Serializable {


     private int id;
     private int value;
     private String description;
     private int question;
     private QuestionnaireQuestion m_QuestionnaireQuestion;

    public QuestionnaireQuestionAnswer() {
    }

    public QuestionnaireQuestionAnswer(int value, String description, int question, QuestionnaireQuestion m_QuestionnaireQuestion) {
       this.value = value;
       this.description = description;
       this.question = question;
       this.m_QuestionnaireQuestion = m_QuestionnaireQuestion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getQuestion() {
        return this.question;
    }
    
    public void setQuestion(int question) {
        this.question = question;
    }
    public QuestionnaireQuestion getM_QuestionnaireQuestion() {
        return this.m_QuestionnaireQuestion;
    }
    
    public void setM_QuestionnaireQuestion(QuestionnaireQuestion m_QuestionnaireQuestion) {
        this.m_QuestionnaireQuestion = m_QuestionnaireQuestion;
    }




}


