package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA



/**
 * Right generated by hbm2java
 */
public class Right  implements java.io.Serializable {


     private int id;
     private int srv;
     private int usr;
     private Service m_Service;
     private User m_User;

    public Right() {
    }

    public Right(int srv, int usr, Service m_Service, User m_User) {
       this.srv = srv;
       this.usr = usr;
       this.m_Service = m_Service;
       this.m_User = m_User;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getSrv() {
        return this.srv;
    }
    
    public void setSrv(int srv) {
        this.srv = srv;
    }
    public int getUsr() {
        return this.usr;
    }
    
    public void setUsr(int usr) {
        this.usr = usr;
    }
    public Service getM_Service() {
        return this.m_Service;
    }
    
    public void setM_Service(Service m_Service) {
        this.m_Service = m_Service;
    }
    public User getM_User() {
        return this.m_User;
    }
    
    public void setM_User(User m_User) {
        this.m_User = m_User;
    }




}


