package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service  implements java.io.Serializable {


     private int id;
     private String name;
     private Set Rights = new HashSet(0);

    public Service() {
    }

    public Service(String name, Set Rights) {
       this.name = name;
       this.Rights = Rights;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRights() {
        return this.Rights;
    }
    
    public void setRights(Set Rights) {
        this.Rights = Rights;
    }




}


