package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SocioDemographicData generated by hbm2java
 */
public class SocioDemographicData  implements java.io.Serializable {


     private int id;
     private int Age;
     private int Gender;
     private int MaritalStatus;
     private int Children;
     private int LivingWith;
     private GenderT m_GenderT;
     private MaritalStatusT m_MaritalStatusT;
     private LivingWithT m_LivingWithT;
     private Set Carers = new HashSet(0);
     private Set Patients = new HashSet(0);

    public SocioDemographicData() {
    }

    public SocioDemographicData(int Age, int Gender, int MaritalStatus, int Children, int LivingWith, GenderT m_GenderT, MaritalStatusT m_MaritalStatusT, LivingWithT m_LivingWithT, Set Carers, Set Patients) {
       this.Age = Age;
       this.Gender = Gender;
       this.MaritalStatus = MaritalStatus;
       this.Children = Children;
       this.LivingWith = LivingWith;
       this.m_GenderT = m_GenderT;
       this.m_MaritalStatusT = m_MaritalStatusT;
       this.m_LivingWithT = m_LivingWithT;
       this.Carers = Carers;
       this.Patients = Patients;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getAge() {
        return this.Age;
    }
    
    public void setAge(int Age) {
        this.Age = Age;
    }
    public int getGender() {
        return this.Gender;
    }
    
    public void setGender(int Gender) {
        this.Gender = Gender;
    }
    public int getMaritalStatus() {
        return this.MaritalStatus;
    }
    
    public void setMaritalStatus(int MaritalStatus) {
        this.MaritalStatus = MaritalStatus;
    }
    public int getChildren() {
        return this.Children;
    }
    
    public void setChildren(int Children) {
        this.Children = Children;
    }
    public int getLivingWith() {
        return this.LivingWith;
    }
    
    public void setLivingWith(int LivingWith) {
        this.LivingWith = LivingWith;
    }
    public GenderT getM_GenderT() {
        return this.m_GenderT;
    }
    
    public void setM_GenderT(GenderT m_GenderT) {
        this.m_GenderT = m_GenderT;
    }
    public MaritalStatusT getM_MaritalStatusT() {
        return this.m_MaritalStatusT;
    }
    
    public void setM_MaritalStatusT(MaritalStatusT m_MaritalStatusT) {
        this.m_MaritalStatusT = m_MaritalStatusT;
    }
    public LivingWithT getM_LivingWithT() {
        return this.m_LivingWithT;
    }
    
    public void setM_LivingWithT(LivingWithT m_LivingWithT) {
        this.m_LivingWithT = m_LivingWithT;
    }
    public Set getCarers() {
        return this.Carers;
    }
    
    public void setCarers(Set Carers) {
        this.Carers = Carers;
    }
    public Set getPatients() {
        return this.Patients;
    }
    
    public void setPatients(Set Patients) {
        this.Patients = Patients;
    }




}


