package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * typeT generated by hbm2java
 */
public class typeT  implements java.io.Serializable {


     private int id;
     private int Code;
     private String Description;
     private Set Users = new HashSet(0);

    public typeT() {
    }

    public typeT(int Code, String Description, Set Users) {
       this.Code = Code;
       this.Description = Description;
       this.Users = Users;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCode() {
        return this.Code;
    }
    
    public void setCode(int Code) {
        this.Code = Code;
    }
    public String getDescription() {
        return this.Description;
    }
    
    public void setDescription(String Description) {
        this.Description = Description;
    }
    public Set getUsers() {
        return this.Users;
    }
    
    public void setUsers(Set Users) {
        this.Users = Users;
    }




}


