package com.aladdin.xsd;
// default package
// Generated Apr 23, 2010 2:52:40 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String login;
     private String password;
     private int type;
     private typeT m_typeT;
     private Set Rights = new HashSet(0);

    public User() {
    }

    public User(String login, String password, int type, typeT m_typeT, Set Rights) {
       this.login = login;
       this.password = password;
       this.type = type;
       this.m_typeT = m_typeT;
       this.Rights = Rights;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public typeT getM_typeT() {
        return this.m_typeT;
    }
    
    public void setM_typeT(typeT m_typeT) {
        this.m_typeT = m_typeT;
    }
    public Set getRights() {
        return this.Rights;
    }
    
    public void setRights(Set Rights) {
        this.Rights = Rights;
    }




}


