//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 05:50:45 PM CEST 
//


package iface;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PatientAssessment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientAssessment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PatientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DateOfAssessment" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Aetology" type="{http://aladdin.com/xsd}SystemParameter"/>
 *         &lt;element name="TimeEllapsedSinceDiagnosed" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="RelevantPathologyAntecedents" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comorbidity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CharlsonComorbidityIndex" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="BarthelIndex" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="LawtonIndex" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="MMSE" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="MDRS" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="BlessedScalePart1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="BlessedScalePart2" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="BlessedScalePart3" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="ChecklistMBP" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="NPQI_Severity" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="NPQI_Stress" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="GDS" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="Falls" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Incontinence" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Delirium" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Immobility" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SensorialDeficits" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PharmacologicalTreatment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClinicalData" type="{http://aladdin.com/xsd}Measurement" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientAssessment", propOrder = {
    "id",
    "patientID",
    "dateOfAssessment",
    "aetology",
    "timeEllapsedSinceDiagnosed",
    "severity",
    "relevantPathologyAntecedents",
    "comorbidity",
    "charlsonComorbidityIndex",
    "barthelIndex",
    "lawtonIndex",
    "mmse",
    "mdrs",
    "blessedScalePart1",
    "blessedScalePart2",
    "blessedScalePart3",
    "checklistMBP",
    "npqiSeverity",
    "npqiStress",
    "gds",
    "falls",
    "incontinence",
    "delirium",
    "immobility",
    "sensorialDeficits",
    "pharmacologicalTreatment",
    "clinicalData"
})
public class PatientAssessment {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "PatientID", required = true)
    protected String patientID;
    @XmlElement(name = "DateOfAssessment", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateOfAssessment;
    @XmlElement(name = "Aetology", required = true)
    protected SystemParameter aetology;
    @XmlElement(name = "TimeEllapsedSinceDiagnosed")
    @XmlSchemaType(name = "unsignedByte")
    protected short timeEllapsedSinceDiagnosed;
    @XmlElement(name = "Severity")
    @XmlSchemaType(name = "unsignedByte")
    protected short severity;
    @XmlElement(name = "RelevantPathologyAntecedents")
    protected String relevantPathologyAntecedents;
    @XmlElement(name = "Comorbidity")
    protected String comorbidity;
    @XmlElement(name = "CharlsonComorbidityIndex")
    @XmlSchemaType(name = "unsignedByte")
    protected Short charlsonComorbidityIndex;
    @XmlElement(name = "BarthelIndex")
    @XmlSchemaType(name = "unsignedByte")
    protected Short barthelIndex;
    @XmlElement(name = "LawtonIndex")
    @XmlSchemaType(name = "unsignedByte")
    protected Short lawtonIndex;
    @XmlElement(name = "MMSE")
    @XmlSchemaType(name = "unsignedByte")
    protected short mmse;
    @XmlElement(name = "MDRS")
    @XmlSchemaType(name = "unsignedByte")
    protected Short mdrs;
    @XmlElement(name = "BlessedScalePart1")
    protected BigDecimal blessedScalePart1;
    @XmlElement(name = "BlessedScalePart2")
    @XmlSchemaType(name = "unsignedByte")
    protected Short blessedScalePart2;
    @XmlElement(name = "BlessedScalePart3")
    @XmlSchemaType(name = "unsignedByte")
    protected Short blessedScalePart3;
    @XmlElement(name = "ChecklistMBP")
    @XmlSchemaType(name = "unsignedByte")
    protected Short checklistMBP;
    @XmlElement(name = "NPQI_Severity")
    @XmlSchemaType(name = "unsignedByte")
    protected Short npqiSeverity;
    @XmlElement(name = "NPQI_Stress")
    @XmlSchemaType(name = "unsignedByte")
    protected Short npqiStress;
    @XmlElement(name = "GDS")
    @XmlSchemaType(name = "unsignedByte")
    protected Short gds;
    @XmlElement(name = "Falls")
    protected Boolean falls;
    @XmlElement(name = "Incontinence")
    protected Boolean incontinence;
    @XmlElement(name = "Delirium")
    protected Boolean delirium;
    @XmlElement(name = "Immobility")
    protected Boolean immobility;
    @XmlElement(name = "SensorialDeficits")
    protected Boolean sensorialDeficits;
    @XmlElement(name = "PharmacologicalTreatment")
    protected String pharmacologicalTreatment;
    @XmlElement(name = "ClinicalData", required = true)
    protected List<Measurement> clinicalData;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the patientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientID() {
        return patientID;
    }

    /**
     * Sets the value of the patientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientID(String value) {
        this.patientID = value;
    }

    /**
     * Gets the value of the dateOfAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfAssessment() {
        return dateOfAssessment;
    }

    /**
     * Sets the value of the dateOfAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfAssessment(XMLGregorianCalendar value) {
        this.dateOfAssessment = value;
    }

    /**
     * Gets the value of the aetology property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParameter }
     *     
     */
    public SystemParameter getAetology() {
        return aetology;
    }

    /**
     * Sets the value of the aetology property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParameter }
     *     
     */
    public void setAetology(SystemParameter value) {
        this.aetology = value;
    }

    /**
     * Gets the value of the timeEllapsedSinceDiagnosed property.
     * 
     */
    public short getTimeEllapsedSinceDiagnosed() {
        return timeEllapsedSinceDiagnosed;
    }

    /**
     * Sets the value of the timeEllapsedSinceDiagnosed property.
     * 
     */
    public void setTimeEllapsedSinceDiagnosed(short value) {
        this.timeEllapsedSinceDiagnosed = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     */
    public short getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     */
    public void setSeverity(short value) {
        this.severity = value;
    }

    /**
     * Gets the value of the relevantPathologyAntecedents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelevantPathologyAntecedents() {
        return relevantPathologyAntecedents;
    }

    /**
     * Sets the value of the relevantPathologyAntecedents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelevantPathologyAntecedents(String value) {
        this.relevantPathologyAntecedents = value;
    }

    /**
     * Gets the value of the comorbidity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComorbidity() {
        return comorbidity;
    }

    /**
     * Sets the value of the comorbidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComorbidity(String value) {
        this.comorbidity = value;
    }

    /**
     * Gets the value of the charlsonComorbidityIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCharlsonComorbidityIndex() {
        return charlsonComorbidityIndex;
    }

    /**
     * Sets the value of the charlsonComorbidityIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCharlsonComorbidityIndex(Short value) {
        this.charlsonComorbidityIndex = value;
    }

    /**
     * Gets the value of the barthelIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getBarthelIndex() {
        return barthelIndex;
    }

    /**
     * Sets the value of the barthelIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setBarthelIndex(Short value) {
        this.barthelIndex = value;
    }

    /**
     * Gets the value of the lawtonIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getLawtonIndex() {
        return lawtonIndex;
    }

    /**
     * Sets the value of the lawtonIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setLawtonIndex(Short value) {
        this.lawtonIndex = value;
    }

    /**
     * Gets the value of the mmse property.
     * 
     */
    public short getMMSE() {
        return mmse;
    }

    /**
     * Sets the value of the mmse property.
     * 
     */
    public void setMMSE(short value) {
        this.mmse = value;
    }

    /**
     * Gets the value of the mdrs property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMDRS() {
        return mdrs;
    }

    /**
     * Sets the value of the mdrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMDRS(Short value) {
        this.mdrs = value;
    }

    /**
     * Gets the value of the blessedScalePart1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBlessedScalePart1() {
        return blessedScalePart1;
    }

    /**
     * Sets the value of the blessedScalePart1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBlessedScalePart1(BigDecimal value) {
        this.blessedScalePart1 = value;
    }

    /**
     * Gets the value of the blessedScalePart2 property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getBlessedScalePart2() {
        return blessedScalePart2;
    }

    /**
     * Sets the value of the blessedScalePart2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setBlessedScalePart2(Short value) {
        this.blessedScalePart2 = value;
    }

    /**
     * Gets the value of the blessedScalePart3 property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getBlessedScalePart3() {
        return blessedScalePart3;
    }

    /**
     * Sets the value of the blessedScalePart3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setBlessedScalePart3(Short value) {
        this.blessedScalePart3 = value;
    }

    /**
     * Gets the value of the checklistMBP property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getChecklistMBP() {
        return checklistMBP;
    }

    /**
     * Sets the value of the checklistMBP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setChecklistMBP(Short value) {
        this.checklistMBP = value;
    }

    /**
     * Gets the value of the npqiSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNPQISeverity() {
        return npqiSeverity;
    }

    /**
     * Sets the value of the npqiSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNPQISeverity(Short value) {
        this.npqiSeverity = value;
    }

    /**
     * Gets the value of the npqiStress property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNPQIStress() {
        return npqiStress;
    }

    /**
     * Sets the value of the npqiStress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNPQIStress(Short value) {
        this.npqiStress = value;
    }

    /**
     * Gets the value of the gds property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getGDS() {
        return gds;
    }

    /**
     * Sets the value of the gds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setGDS(Short value) {
        this.gds = value;
    }

    /**
     * Gets the value of the falls property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFalls() {
        return falls;
    }

    /**
     * Sets the value of the falls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFalls(Boolean value) {
        this.falls = value;
    }

    /**
     * Gets the value of the incontinence property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncontinence() {
        return incontinence;
    }

    /**
     * Sets the value of the incontinence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncontinence(Boolean value) {
        this.incontinence = value;
    }

    /**
     * Gets the value of the delirium property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDelirium() {
        return delirium;
    }

    /**
     * Sets the value of the delirium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDelirium(Boolean value) {
        this.delirium = value;
    }

    /**
     * Gets the value of the immobility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImmobility() {
        return immobility;
    }

    /**
     * Sets the value of the immobility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImmobility(Boolean value) {
        this.immobility = value;
    }

    /**
     * Gets the value of the sensorialDeficits property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSensorialDeficits() {
        return sensorialDeficits;
    }

    /**
     * Sets the value of the sensorialDeficits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSensorialDeficits(Boolean value) {
        this.sensorialDeficits = value;
    }

    /**
     * Gets the value of the pharmacologicalTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharmacologicalTreatment() {
        return pharmacologicalTreatment;
    }

    /**
     * Sets the value of the pharmacologicalTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharmacologicalTreatment(String value) {
        this.pharmacologicalTreatment = value;
    }

    /**
     * Gets the value of the clinicalData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clinicalData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClinicalData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Measurement }
     * 
     * 
     */
    public List<Measurement> getClinicalData() {
        if (clinicalData == null) {
            clinicalData = new ArrayList<Measurement>();
        }
        return this.clinicalData;
    }

}
