//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 05:50:45 PM CEST 
//


package iface;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SocioDemographicData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SocioDemographicData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Age" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="Gender" type="{http://aladdin.com/xsd}SystemParameter"/>
 *         &lt;element name="MaritalStatus" type="{http://aladdin.com/xsd}SystemParameter"/>
 *         &lt;element name="Children" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="LivingWith" type="{http://aladdin.com/xsd}SystemParameter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SocioDemographicData", propOrder = {
    "age",
    "gender",
    "maritalStatus",
    "children",
    "livingWith"
})
public class SocioDemographicData {

    @XmlElement(name = "Age")
    @XmlSchemaType(name = "unsignedByte")
    protected short age;
    @XmlElement(name = "Gender", required = true)
    protected SystemParameter gender;
    @XmlElement(name = "MaritalStatus", required = true)
    protected SystemParameter maritalStatus;
    @XmlElement(name = "Children")
    @XmlSchemaType(name = "unsignedByte")
    protected short children;
    @XmlElement(name = "LivingWith", required = true)
    protected SystemParameter livingWith;

    /**
     * Gets the value of the age property.
     * 
     */
    public short getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     */
    public void setAge(short value) {
        this.age = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParameter }
     *     
     */
    public SystemParameter getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParameter }
     *     
     */
    public void setGender(SystemParameter value) {
        this.gender = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParameter }
     *     
     */
    public SystemParameter getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParameter }
     *     
     */
    public void setMaritalStatus(SystemParameter value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the children property.
     * 
     */
    public short getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     */
    public void setChildren(short value) {
        this.children = value;
    }

    /**
     * Gets the value of the livingWith property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParameter }
     *     
     */
    public SystemParameter getLivingWith() {
        return livingWith;
    }

    /**
     * Sets the value of the livingWith property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParameter }
     *     
     */
    public void setLivingWith(SystemParameter value) {
        this.livingWith = value;
    }

}
