package com.aladdin.sc;

import org.hibernate.SQLQuery;

public class Dict {
	
	static private String getData (String code, String type, org.hibernate.Session s) {
		SQLQuery q = s.createSQLQuery("SELECT description from dict where code = '" + code + "' and type = '" + type + "'");
		Object[] data = q.list().toArray();
		if (data.length > 0) {
			return (String) ((Object[])data[0])[0];
		}
		return "";
	}

	static public String getGenderDescription (String code, org.hibernate.Session s) {
		return getData (code, "gender", s);
//		if (code == 1) return "male";
//		if (code == 2) return "female";
	}
	
	static public String getMaritalStatusDescription (String code, org.hibernate.Session s) {
		return getData (code, "marital", s);
/*		if (code == 1) return "widow";
		if (code == 2) return "married";
		if (code == 3) return "single";
		if (code == 4) return "divorced";*/
	}
	
	static public String getLivingWithDescription (String code, org.hibernate.Session s) {
		return getData (code, "livingwith", s);
/*		if (code == 0) return "alone";
		if (code == 1) return "with son/daugther";
		if (code == 2) return "with partner";
		if (code == 3) return "with partner + son/daugther";
		if (code == 4) return "with partner + son/daugther + s/d in law";
		if (code == 5) return "with partner + s/d + s/d in law + grandson/d";*/
	}
	
	static public String getMeasurementType (String code, org.hibernate.Session s) {
		return getData (code, "measurement", s);
//		if (code == 1) return "Blood pressure";
//		if (code == 2) return "Weight";
	}
	
	static public String getTaskDescription (String code, org.hibernate.Session s) {
		return getData (code, "task", s);
		/*switch (code) {
			case 1: return "Patient Questionnaire"; 
			case 2: return "Carer Questionnaire"; 
			case 3: return "Blood Pressure Measurement"; 
			case 4: return "Weight Measurement"; 
			case 5: return "Cognitive Game Task";
			case 6: return "Activity Monitor Measurement";
			case 7: return "Exercise";
			default: return "";
		}*/
	}
	
	static public String getTaskStatusType (String code, org.hibernate.Session s) {
		return getData (code, "taskstatus", s);
/*		if (code == 1) return "pending";
		if (code == 2) return "canceled";
		if (code == 3) return "completed";*/
	}
	
	static public String getTypeOfWarningDesciption (String code, org.hibernate.Session s) {
		return getData (code, "warningtype", s);
//		if (code == 1) return "manual";
//		if (code == 2) return "autogenerated";
	}
	
	static public String getEffectOfWarningDesciption (String code, org.hibernate.Session s) {
		return getData (code, "warningeffect", s);
//		if (code == 1) return "stroke";
	}
	
	static public String getIndicatorOfWarningDesciption (String code, org.hibernate.Session s) {
		return getData (code, "warningindicator", s);
//		if (code == 1) return "high blood pressure";
//		if (code == 2) return "falls";
	}
	
	static public String getRisklevelOfWarningDesciption (String code, org.hibernate.Session s) {
		return getData (code, "warningrisk", s);
//		if (code == 1) return "high";
//		if (code == 2) return "low";
	}
	
	static public String getEmergencylevelOfWarningDesciption (String code, org.hibernate.Session s) {
		return getData (code, "warningemergency", s);
//		if (code == 1) return "immediate attention";
//		if (code == 2) return "attention";
	}
	
}
