//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.11 at 12:12:51 PM CEST 
//


package com.aladdin.xsd.iface;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CarerAssessment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarerAssessment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CarerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClinicianID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DateOfAssessment" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="RelevantHealthProblem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SeverityOfBurden" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="EmotionalOrMentalDisorders" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PsychoactiveDrugs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QualityOfLife" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarerAssessment", propOrder = {
    "id",
    "carerID",
    "clinicianID",
    "dateOfAssessment",
    "relevantHealthProblem",
    "severityOfBurden",
    "emotionalOrMentalDisorders",
    "psychoactiveDrugs",
    "qualityOfLife"
})
public class CarerAssessment {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "CarerID", required = true)
    protected String carerID;
    @XmlElement(name = "ClinicianID", required = true)
    protected String clinicianID;
    @XmlElement(name = "DateOfAssessment", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateOfAssessment;
    @XmlElement(name = "RelevantHealthProblem")
    protected String relevantHealthProblem;
    @XmlElement(name = "SeverityOfBurden")
    @XmlSchemaType(name = "unsignedByte")
    protected short severityOfBurden;
    @XmlElement(name = "EmotionalOrMentalDisorders")
    protected String emotionalOrMentalDisorders;
    @XmlElement(name = "PsychoactiveDrugs")
    protected String psychoactiveDrugs;
    @XmlElement(name = "QualityOfLife")
    @XmlSchemaType(name = "unsignedByte")
    protected Short qualityOfLife;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the carerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarerID() {
        return carerID;
    }

    /**
     * Sets the value of the carerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarerID(String value) {
        this.carerID = value;
    }

    /**
     * Gets the value of the clinicianID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicianID() {
        return clinicianID;
    }

    /**
     * Sets the value of the clinicianID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicianID(String value) {
        this.clinicianID = value;
    }

    /**
     * Gets the value of the dateOfAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfAssessment() {
        return dateOfAssessment;
    }

    /**
     * Sets the value of the dateOfAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfAssessment(XMLGregorianCalendar value) {
        this.dateOfAssessment = value;
    }

    /**
     * Gets the value of the relevantHealthProblem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelevantHealthProblem() {
        return relevantHealthProblem;
    }

    /**
     * Sets the value of the relevantHealthProblem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelevantHealthProblem(String value) {
        this.relevantHealthProblem = value;
    }

    /**
     * Gets the value of the severityOfBurden property.
     * 
     */
    public short getSeverityOfBurden() {
        return severityOfBurden;
    }

    /**
     * Sets the value of the severityOfBurden property.
     * 
     */
    public void setSeverityOfBurden(short value) {
        this.severityOfBurden = value;
    }

    /**
     * Gets the value of the emotionalOrMentalDisorders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmotionalOrMentalDisorders() {
        return emotionalOrMentalDisorders;
    }

    /**
     * Sets the value of the emotionalOrMentalDisorders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmotionalOrMentalDisorders(String value) {
        this.emotionalOrMentalDisorders = value;
    }

    /**
     * Gets the value of the psychoactiveDrugs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsychoactiveDrugs() {
        return psychoactiveDrugs;
    }

    /**
     * Sets the value of the psychoactiveDrugs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsychoactiveDrugs(String value) {
        this.psychoactiveDrugs = value;
    }

    /**
     * Gets the value of the qualityOfLife property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getQualityOfLife() {
        return qualityOfLife;
    }

    /**
     * Sets the value of the qualityOfLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setQualityOfLife(Short value) {
        this.qualityOfLife = value;
    }

}
