//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.11 at 12:12:51 PM CEST 
//


package com.aladdin.xsd.iface;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Patient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Patient">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PersonData" type="{http://aladdin.com/xsd}PersonData"/>
 *         &lt;element name="SD_Data" type="{http://aladdin.com/xsd}SocioDemographicData"/>
 *         &lt;element name="ResponsibleClinicianID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PatientCarerList" type="{http://aladdin.com/xsd}PatientCarer" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Patient", propOrder = {
    "id",
    "personData",
    "sdData",
    "responsibleClinicianID",
    "patientCarerList"
})
public class Patient {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "PersonData", required = true)
    protected PersonData personData;
    @XmlElement(name = "SD_Data", required = true)
    protected SocioDemographicData sdData;
    @XmlElement(name = "ResponsibleClinicianID", required = true)
    protected String responsibleClinicianID;
    @XmlElement(name = "PatientCarerList", required = true)
    protected List<PatientCarer> patientCarerList;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the personData property.
     * 
     * @return
     *     possible object is
     *     {@link PersonData }
     *     
     */
    public PersonData getPersonData() {
        return personData;
    }

    /**
     * Sets the value of the personData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonData }
     *     
     */
    public void setPersonData(PersonData value) {
        this.personData = value;
    }

    /**
     * Gets the value of the sdData property.
     * 
     * @return
     *     possible object is
     *     {@link SocioDemographicData }
     *     
     */
    public SocioDemographicData getSDData() {
        return sdData;
    }

    /**
     * Sets the value of the sdData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocioDemographicData }
     *     
     */
    public void setSDData(SocioDemographicData value) {
        this.sdData = value;
    }

    /**
     * Gets the value of the responsibleClinicianID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsibleClinicianID() {
        return responsibleClinicianID;
    }

    /**
     * Sets the value of the responsibleClinicianID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsibleClinicianID(String value) {
        this.responsibleClinicianID = value;
    }

    /**
     * Gets the value of the patientCarerList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patientCarerList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatientCarerList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatientCarer }
     * 
     * 
     */
    public List<PatientCarer> getPatientCarerList() {
        if (patientCarerList == null) {
            patientCarerList = new ArrayList<PatientCarer>();
        }
        return this.patientCarerList;
    }

}
