#!/bin/sh

for i in `xsd2hbm -x src/schemata.xsd -i SystemParameter --list`; do echo "create $i" && xsd2hbm -x src/schemata.xsd -i SystemParameter -b $i > generated/com/aladdin/xsd/$i.hbm.xml ; done;
