//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.17 at 06:51:57 μμ EET 
//


package org.example.rulemap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CallerID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="LowerLimit" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="UpperLimit" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="GetPrevious" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="HighRiskThresh" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleMap", propOrder = {
    "dataType",
    "callerID",
    "lowerLimit",
    "upperLimit",
    "getPrevious",
    "highRiskThresh"
})
public class RuleMap {

    @XmlElement(name = "DataType", required = true)
    protected String dataType;
    @XmlElement(name = "CallerID")
    protected int callerID;
    @XmlElement(name = "LowerLimit")
    protected double lowerLimit;
    @XmlElement(name = "UpperLimit")
    protected double upperLimit;
    @XmlElement(name = "GetPrevious")
    protected boolean getPrevious;
    @XmlElement(name = "HighRiskThresh")
    protected Double highRiskThresh;

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the callerID property.
     * 
     */
    public int getCallerID() {
        return callerID;
    }

    /**
     * Sets the value of the callerID property.
     * 
     */
    public void setCallerID(int value) {
        this.callerID = value;
    }

    /**
     * Gets the value of the lowerLimit property.
     * 
     */
    public double getLowerLimit() {
        return lowerLimit;
    }

    /**
     * Sets the value of the lowerLimit property.
     * 
     */
    public void setLowerLimit(double value) {
        this.lowerLimit = value;
    }

    /**
     * Gets the value of the upperLimit property.
     * 
     */
    public double getUpperLimit() {
        return upperLimit;
    }

    /**
     * Sets the value of the upperLimit property.
     * 
     */
    public void setUpperLimit(double value) {
        this.upperLimit = value;
    }

    /**
     * Gets the value of the getPrevious property.
     * 
     */
    public boolean isGetPrevious() {
        return getPrevious;
    }

    /**
     * Sets the value of the getPrevious property.
     * 
     */
    public void setGetPrevious(boolean value) {
        this.getPrevious = value;
    }

    /**
     * Gets the value of the highRiskThresh property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHighRiskThresh() {
        return highRiskThresh;
    }

    /**
     * Sets the value of the highRiskThresh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHighRiskThresh(Double value) {
        this.highRiskThresh = value;
    }

}
