//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 04:21:50 PM CEST 
//


package iface;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iface package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iface
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link PersonData }
     * 
     */
    public PersonData createPersonData() {
        return new PersonData();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link CarerAssessment }
     * 
     */
    public CarerAssessment createCarerAssessment() {
        return new CarerAssessment();
    }

    /**
     * Create an instance of {@link PatientInfo }
     * 
     */
    public PatientInfo createPatientInfo() {
        return new PatientInfo();
    }

    /**
     * Create an instance of {@link ClinicianListType }
     * 
     */
    public ClinicianListType createClinicianListType() {
        return new ClinicianListType();
    }

    /**
     * Create an instance of {@link Measurement }
     * 
     */
    public Measurement createMeasurement() {
        return new Measurement();
    }

    /**
     * Create an instance of {@link QuestionnaireAnswerListType }
     * 
     */
    public QuestionnaireAnswerListType createQuestionnaireAnswerListType() {
        return new QuestionnaireAnswerListType();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link OperationResult }
     * 
     */
    public OperationResult createOperationResult() {
        return new OperationResult();
    }

    /**
     * Create an instance of {@link CommunicationListType }
     * 
     */
    public CommunicationListType createCommunicationListType() {
        return new CommunicationListType();
    }

    /**
     * Create an instance of {@link QuestionnaireQuestionAnswer }
     * 
     */
    public QuestionnaireQuestionAnswer createQuestionnaireQuestionAnswer() {
        return new QuestionnaireQuestionAnswer();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link Clinician }
     * 
     */
    public Clinician createClinician() {
        return new Clinician();
    }

    /**
     * Create an instance of {@link CarerInfo }
     * 
     */
    public CarerInfo createCarerInfo() {
        return new CarerInfo();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link QuestionListType }
     * 
     */
    public QuestionListType createQuestionListType() {
        return new QuestionListType();
    }

    /**
     * Create an instance of {@link SearchCriteria }
     * 
     */
    public SearchCriteria createSearchCriteria() {
        return new SearchCriteria();
    }

    /**
     * Create an instance of {@link QuestionAnswerListType }
     * 
     */
    public QuestionAnswerListType createQuestionAnswerListType() {
        return new QuestionAnswerListType();
    }

    /**
     * Create an instance of {@link Communication }
     * 
     */
    public Communication createCommunication() {
        return new Communication();
    }

    /**
     * Create an instance of {@link Question }
     * 
     */
    public Question createQuestion() {
        return new Question();
    }

    /**
     * Create an instance of {@link ClinicianInfo }
     * 
     */
    public ClinicianInfo createClinicianInfo() {
        return new ClinicianInfo();
    }

    /**
     * Create an instance of {@link SocioDemographicData }
     * 
     */
    public SocioDemographicData createSocioDemographicData() {
        return new SocioDemographicData();
    }

    /**
     * Create an instance of {@link ExternalService }
     * 
     */
    public ExternalService createExternalService() {
        return new ExternalService();
    }

    /**
     * Create an instance of {@link AdministratorInfo }
     * 
     */
    public AdministratorInfo createAdministratorInfo() {
        return new AdministratorInfo();
    }

    /**
     * Create an instance of {@link PatientCarerListType }
     * 
     */
    public PatientCarerListType createPatientCarerListType() {
        return new PatientCarerListType();
    }

    /**
     * Create an instance of {@link QuestionnaireInfo }
     * 
     */
    public QuestionnaireInfo createQuestionnaireInfo() {
        return new QuestionnaireInfo();
    }

    /**
     * Create an instance of {@link Carer }
     * 
     */
    public Carer createCarer() {
        return new Carer();
    }

    /**
     * Create an instance of {@link QuestionnaireAnswers }
     * 
     */
    public QuestionnaireAnswers createQuestionnaireAnswers() {
        return new QuestionnaireAnswers();
    }

    /**
     * Create an instance of {@link SystemParameter }
     * 
     */
    public SystemParameter createSystemParameter() {
        return new SystemParameter();
    }

    /**
     * Create an instance of {@link IdentifierListType }
     * 
     */
    public IdentifierListType createIdentifierListType() {
        return new IdentifierListType();
    }

    /**
     * Create an instance of {@link PatientAssessment }
     * 
     */
    public PatientAssessment createPatientAssessment() {
        return new PatientAssessment();
    }

    /**
     * Create an instance of {@link Questionnaire }
     * 
     */
    public Questionnaire createQuestionnaire() {
        return new Questionnaire();
    }

    /**
     * Create an instance of {@link AddressListType }
     * 
     */
    public AddressListType createAddressListType() {
        return new AddressListType();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link Administrator }
     * 
     */
    public Administrator createAdministrator() {
        return new Administrator();
    }

    /**
     * Create an instance of {@link QuestionnaireAnswer }
     * 
     */
    public QuestionnaireAnswer createQuestionnaireAnswer() {
        return new QuestionnaireAnswer();
    }

    /**
     * Create an instance of {@link PatientCarer }
     * 
     */
    public PatientCarer createPatientCarer() {
        return new PatientCarer();
    }

}
