//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 04:21:50 PM CEST 
//


package iface;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Surname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IdentifierList" type="{http://aladdin.com/xsd}IdentifierListType"/>
 *         &lt;element name="AddressList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CommunicationList" type="{http://aladdin.com/xsd}CommunicationListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonData", propOrder = {
    "surname",
    "name",
    "identifierList",
    "addressList",
    "communicationList"
})
public class PersonData {

    @XmlElement(name = "Surname", required = true)
    protected String surname;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "IdentifierList", required = true)
    protected IdentifierListType identifierList;
    @XmlElement(name = "AddressList", required = true)
    protected String addressList;
    @XmlElement(name = "CommunicationList", required = true)
    protected CommunicationListType communicationList;

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the identifierList property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierListType }
     *     
     */
    public IdentifierListType getIdentifierList() {
        return identifierList;
    }

    /**
     * Sets the value of the identifierList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierListType }
     *     
     */
    public void setIdentifierList(IdentifierListType value) {
        this.identifierList = value;
    }

    /**
     * Gets the value of the addressList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressList() {
        return addressList;
    }

    /**
     * Sets the value of the addressList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressList(String value) {
        this.addressList = value;
    }

    /**
     * Gets the value of the communicationList property.
     * 
     * @return
     *     possible object is
     *     {@link CommunicationListType }
     *     
     */
    public CommunicationListType getCommunicationList() {
        return communicationList;
    }

    /**
     * Sets the value of the communicationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationListType }
     *     
     */
    public void setCommunicationList(CommunicationListType value) {
        this.communicationList = value;
    }

}
