//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 05:50:45 PM CEST 
//


package iface;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Warning complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Warning">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DateTimeOfWarning" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Effect" type="{http://aladdin.com/xsd}SystemParameter"/>
 *         &lt;element name="Indicator" type="{http://aladdin.com/xsd}SystemParameter"/>
 *         &lt;element name="RiskLevel" type="{http://aladdin.com/xsd}SystemParameter"/>
 *         &lt;element name="JustificationText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EmergencyLevel" type="{http://aladdin.com/xsd}SystemParameter"/>
 *         &lt;element name="PatientID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Delivered" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Warning", propOrder = {
    "id",
    "dateTimeOfWarning",
    "effect",
    "indicator",
    "riskLevel",
    "justificationText",
    "emergencyLevel",
    "patientID",
    "delivered"
})
public class Warning {

    @XmlElement(name = "ID", required = true)
    protected String id;
    @XmlElement(name = "DateTimeOfWarning", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTimeOfWarning;
    @XmlElement(name = "Effect", required = true)
    protected SystemParameter effect;
    @XmlElement(name = "Indicator", required = true)
    protected SystemParameter indicator;
    @XmlElement(name = "RiskLevel", required = true)
    protected SystemParameter riskLevel;
    @XmlElement(name = "JustificationText", required = true)
    protected String justificationText;
    @XmlElement(name = "EmergencyLevel", required = true)
    protected SystemParameter emergencyLevel;
    @XmlElement(name = "PatientID", required = true)
    protected String patientID;
    @XmlElement(name = "Delivered")
    protected boolean delivered;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the dateTimeOfWarning property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeOfWarning() {
        return dateTimeOfWarning;
    }

    /**
     * Sets the value of the dateTimeOfWarning property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeOfWarning(XMLGregorianCalendar value) {
        this.dateTimeOfWarning = value;
    }

    /**
     * Gets the value of the effect property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParameter }
     *     
     */
    public SystemParameter getEffect() {
        return effect;
    }

    /**
     * Sets the value of the effect property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParameter }
     *     
     */
    public void setEffect(SystemParameter value) {
        this.effect = value;
    }

    /**
     * Gets the value of the indicator property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParameter }
     *     
     */
    public SystemParameter getIndicator() {
        return indicator;
    }

    /**
     * Sets the value of the indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParameter }
     *     
     */
    public void setIndicator(SystemParameter value) {
        this.indicator = value;
    }

    /**
     * Gets the value of the riskLevel property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParameter }
     *     
     */
    public SystemParameter getRiskLevel() {
        return riskLevel;
    }

    /**
     * Sets the value of the riskLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParameter }
     *     
     */
    public void setRiskLevel(SystemParameter value) {
        this.riskLevel = value;
    }

    /**
     * Gets the value of the justificationText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJustificationText() {
        return justificationText;
    }

    /**
     * Sets the value of the justificationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJustificationText(String value) {
        this.justificationText = value;
    }

    /**
     * Gets the value of the emergencyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link SystemParameter }
     *     
     */
    public SystemParameter getEmergencyLevel() {
        return emergencyLevel;
    }

    /**
     * Sets the value of the emergencyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemParameter }
     *     
     */
    public void setEmergencyLevel(SystemParameter value) {
        this.emergencyLevel = value;
    }

    /**
     * Gets the value of the patientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientID() {
        return patientID;
    }

    /**
     * Sets the value of the patientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientID(String value) {
        this.patientID = value;
    }

    /**
     * Gets the value of the delivered property.
     * 
     */
    public boolean isDelivered() {
        return delivered;
    }

    /**
     * Sets the value of the delivered property.
     * 
     */
    public void setDelivered(boolean value) {
        this.delivered = value;
    }

}
