package com.aladdin.sc.db;
// Generated Jun 17, 2010 2:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Carer generated by hbm2java
 */
public class Carer  implements java.io.Serializable {


     private Integer id;
     private Integer persondata;
     private Integer sd;
     private PersonData m_PersonDatapersondata;
     private SocioDemographicData m_SocioDemographicDatasd;
     private Set CarerAssessments = new HashSet(0);
     private Set PatientCarers1 = new HashSet(0);

    public Carer() {
    }

    public Carer(Integer persondata, Integer sd, PersonData m_PersonDatapersondata, SocioDemographicData m_SocioDemographicDatasd, Set CarerAssessments, Set PatientCarers1) {
       this.persondata = persondata;
       this.sd = sd;
       this.m_PersonDatapersondata = m_PersonDatapersondata;
       this.m_SocioDemographicDatasd = m_SocioDemographicDatasd;
       this.CarerAssessments = CarerAssessments;
       this.PatientCarers1 = PatientCarers1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPersondata() {
        return this.persondata;
    }
    
    public void setPersondata(Integer persondata) {
        this.persondata = persondata;
    }
    public Integer getSd() {
        return this.sd;
    }
    
    public void setSd(Integer sd) {
        this.sd = sd;
    }
    public PersonData getM_PersonDatapersondata() {
        return this.m_PersonDatapersondata;
    }
    
    public void setM_PersonDatapersondata(PersonData m_PersonDatapersondata) {
        this.m_PersonDatapersondata = m_PersonDatapersondata;
    }
    public SocioDemographicData getM_SocioDemographicDatasd() {
        return this.m_SocioDemographicDatasd;
    }
    
    public void setM_SocioDemographicDatasd(SocioDemographicData m_SocioDemographicDatasd) {
        this.m_SocioDemographicDatasd = m_SocioDemographicDatasd;
    }
    public Set getCarerAssessments() {
        return this.CarerAssessments;
    }
    
    public void setCarerAssessments(Set CarerAssessments) {
        this.CarerAssessments = CarerAssessments;
    }
    public Set getPatientCarers1() {
        return this.PatientCarers1;
    }
    
    public void setPatientCarers1(Set PatientCarers1) {
        this.PatientCarers1 = PatientCarers1;
    }




}


