package com.aladdin.sc.db;
// Generated Jun 17, 2010 2:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Clinician generated by hbm2java
 */
public class Clinician  implements java.io.Serializable {


     private Integer id;
     private Integer persondata;
     private PersonData m_PersonDatapersondata;
     private Set Patients = new HashSet(0);

    public Clinician() {
    }

    public Clinician(Integer persondata, PersonData m_PersonDatapersondata, Set Patients) {
       this.persondata = persondata;
       this.m_PersonDatapersondata = m_PersonDatapersondata;
       this.Patients = Patients;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPersondata() {
        return this.persondata;
    }
    
    public void setPersondata(Integer persondata) {
        this.persondata = persondata;
    }
    public PersonData getM_PersonDatapersondata() {
        return this.m_PersonDatapersondata;
    }
    
    public void setM_PersonDatapersondata(PersonData m_PersonDatapersondata) {
        this.m_PersonDatapersondata = m_PersonDatapersondata;
    }
    public Set getPatients() {
        return this.Patients;
    }
    
    public void setPatients(Set Patients) {
        this.Patients = Patients;
    }




}


