package com.aladdin.sc.db;
// Generated Jun 17, 2010 2:46:26 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Measurement generated by hbm2java
 */
public class Measurement  implements java.io.Serializable {


     private Integer id;
     private String type;
     private BigDecimal value;
     private Timestamp datetime;
     private String units;
     private BigDecimal lowerlimit;
     private BigDecimal upperlimit;
     private Integer patient;
     private Integer task;
     private PatientAssessment m_PatientAssessmentpatient;
     private Task m_Tasktask;

    public Measurement() {
    }

    public Measurement(String type, BigDecimal value, Timestamp datetime, String units, BigDecimal lowerlimit, BigDecimal upperlimit, Integer patient, Integer task, PatientAssessment m_PatientAssessmentpatient, Task m_Tasktask) {
       this.type = type;
       this.value = value;
       this.datetime = datetime;
       this.units = units;
       this.lowerlimit = lowerlimit;
       this.upperlimit = upperlimit;
       this.patient = patient;
       this.task = task;
       this.m_PatientAssessmentpatient = m_PatientAssessmentpatient;
       this.m_Tasktask = m_Tasktask;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }
    public Timestamp getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Timestamp datetime) {
        this.datetime = datetime;
    }
    public String getUnits() {
        return this.units;
    }
    
    public void setUnits(String units) {
        this.units = units;
    }
    public BigDecimal getLowerlimit() {
        return this.lowerlimit;
    }
    
    public void setLowerlimit(BigDecimal lowerlimit) {
        this.lowerlimit = lowerlimit;
    }
    public BigDecimal getUpperlimit() {
        return this.upperlimit;
    }
    
    public void setUpperlimit(BigDecimal upperlimit) {
        this.upperlimit = upperlimit;
    }
    public Integer getPatient() {
        return this.patient;
    }
    
    public void setPatient(Integer patient) {
        this.patient = patient;
    }
    public Integer getTask() {
        return this.task;
    }
    
    public void setTask(Integer task) {
        this.task = task;
    }
    public PatientAssessment getM_PatientAssessmentpatient() {
        return this.m_PatientAssessmentpatient;
    }
    
    public void setM_PatientAssessmentpatient(PatientAssessment m_PatientAssessmentpatient) {
        this.m_PatientAssessmentpatient = m_PatientAssessmentpatient;
    }
    public Task getM_Tasktask() {
        return this.m_Tasktask;
    }
    
    public void setM_Tasktask(Task m_Tasktask) {
        this.m_Tasktask = m_Tasktask;
    }




}


