package com.aladdin.sc.db;
// Generated Jun 17, 2010 2:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private Integer id;
     private Integer persondata;
     private Integer sd;
     private Integer clinician;
     private Set PatientAssessments = new HashSet(0);
     private PersonData m_PersonDatapersondata;
     private SocioDemographicData m_SocioDemographicDatasd;
     private Clinician m_Clinicianclinician;
     private Set PatientCarers1 = new HashSet(0);

    public Patient() {
    }

    public Patient(Integer persondata, Integer sd, Integer clinician, Set PatientAssessments, PersonData m_PersonDatapersondata, SocioDemographicData m_SocioDemographicDatasd, Clinician m_Clinicianclinician, Set PatientCarers1) {
       this.persondata = persondata;
       this.sd = sd;
       this.clinician = clinician;
       this.PatientAssessments = PatientAssessments;
       this.m_PersonDatapersondata = m_PersonDatapersondata;
       this.m_SocioDemographicDatasd = m_SocioDemographicDatasd;
       this.m_Clinicianclinician = m_Clinicianclinician;
       this.PatientCarers1 = PatientCarers1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPersondata() {
        return this.persondata;
    }
    
    public void setPersondata(Integer persondata) {
        this.persondata = persondata;
    }
    public Integer getSd() {
        return this.sd;
    }
    
    public void setSd(Integer sd) {
        this.sd = sd;
    }
    public Integer getClinician() {
        return this.clinician;
    }
    
    public void setClinician(Integer clinician) {
        this.clinician = clinician;
    }
    public Set getPatientAssessments() {
        return this.PatientAssessments;
    }
    
    public void setPatientAssessments(Set PatientAssessments) {
        this.PatientAssessments = PatientAssessments;
    }
    public PersonData getM_PersonDatapersondata() {
        return this.m_PersonDatapersondata;
    }
    
    public void setM_PersonDatapersondata(PersonData m_PersonDatapersondata) {
        this.m_PersonDatapersondata = m_PersonDatapersondata;
    }
    public SocioDemographicData getM_SocioDemographicDatasd() {
        return this.m_SocioDemographicDatasd;
    }
    
    public void setM_SocioDemographicDatasd(SocioDemographicData m_SocioDemographicDatasd) {
        this.m_SocioDemographicDatasd = m_SocioDemographicDatasd;
    }
    public Clinician getM_Clinicianclinician() {
        return this.m_Clinicianclinician;
    }
    
    public void setM_Clinicianclinician(Clinician m_Clinicianclinician) {
        this.m_Clinicianclinician = m_Clinicianclinician;
    }
    public Set getPatientCarers1() {
        return this.PatientCarers1;
    }
    
    public void setPatientCarers1(Set PatientCarers1) {
        this.PatientCarers1 = PatientCarers1;
    }




}


