package com.aladdin.sc.db;
// Generated Jun 17, 2010 2:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * PersonData generated by hbm2java
 */
public class PersonData  implements java.io.Serializable {


     private Integer id;
     private String Surname;
     private String Name;
     private Set Identifiers = new HashSet(0);
     private Set Addresss1 = new HashSet(0);
     private Set Communications11 = new HashSet(0);
     private Set Clinicians111 = new HashSet(0);
     private Set Carers1111 = new HashSet(0);
     private Set Patients11111 = new HashSet(0);
     private Set Administrators111111 = new HashSet(0);

    public PersonData() {
    }

    public PersonData(String Surname, String Name, Set Identifiers, Set Addresss1, Set Communications11, Set Clinicians111, Set Carers1111, Set Patients11111, Set Administrators111111) {
       this.Surname = Surname;
       this.Name = Name;
       this.Identifiers = Identifiers;
       this.Addresss1 = Addresss1;
       this.Communications11 = Communications11;
       this.Clinicians111 = Clinicians111;
       this.Carers1111 = Carers1111;
       this.Patients11111 = Patients11111;
       this.Administrators111111 = Administrators111111;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSurname() {
        return this.Surname;
    }
    
    public void setSurname(String Surname) {
        this.Surname = Surname;
    }
    public String getName() {
        return this.Name;
    }
    
    public void setName(String Name) {
        this.Name = Name;
    }
    public Set getIdentifiers() {
        return this.Identifiers;
    }
    
    public void setIdentifiers(Set Identifiers) {
        this.Identifiers = Identifiers;
    }
    public Set getAddresss1() {
        return this.Addresss1;
    }
    
    public void setAddresss1(Set Addresss1) {
        this.Addresss1 = Addresss1;
    }
    public Set getCommunications11() {
        return this.Communications11;
    }
    
    public void setCommunications11(Set Communications11) {
        this.Communications11 = Communications11;
    }
    public Set getClinicians111() {
        return this.Clinicians111;
    }
    
    public void setClinicians111(Set Clinicians111) {
        this.Clinicians111 = Clinicians111;
    }
    public Set getCarers1111() {
        return this.Carers1111;
    }
    
    public void setCarers1111(Set Carers1111) {
        this.Carers1111 = Carers1111;
    }
    public Set getPatients11111() {
        return this.Patients11111;
    }
    
    public void setPatients11111(Set Patients11111) {
        this.Patients11111 = Patients11111;
    }
    public Set getAdministrators111111() {
        return this.Administrators111111;
    }
    
    public void setAdministrators111111(Set Administrators111111) {
        this.Administrators111111 = Administrators111111;
    }




}


