package com.aladdin.sc.db;
// Generated Jun 17, 2010 2:46:26 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SocioDemographicData generated by hbm2java
 */
public class SocioDemographicData  implements java.io.Serializable {


     private Integer id;
     private Integer Age;
     private Integer Gender;
     private Integer MaritalStatus;
     private Integer Children;
     private Integer LivingWith;
     private Set Carers = new HashSet(0);
     private Set Patients1 = new HashSet(0);

    public SocioDemographicData() {
    }

    public SocioDemographicData(Integer Age, Integer Gender, Integer MaritalStatus, Integer Children, Integer LivingWith, Set Carers, Set Patients1) {
       this.Age = Age;
       this.Gender = Gender;
       this.MaritalStatus = MaritalStatus;
       this.Children = Children;
       this.LivingWith = LivingWith;
       this.Carers = Carers;
       this.Patients1 = Patients1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getAge() {
        return this.Age;
    }
    
    public void setAge(Integer Age) {
        this.Age = Age;
    }
    public Integer getGender() {
        return this.Gender;
    }
    
    public void setGender(Integer Gender) {
        this.Gender = Gender;
    }
    public Integer getMaritalStatus() {
        return this.MaritalStatus;
    }
    
    public void setMaritalStatus(Integer MaritalStatus) {
        this.MaritalStatus = MaritalStatus;
    }
    public Integer getChildren() {
        return this.Children;
    }
    
    public void setChildren(Integer Children) {
        this.Children = Children;
    }
    public Integer getLivingWith() {
        return this.LivingWith;
    }
    
    public void setLivingWith(Integer LivingWith) {
        this.LivingWith = LivingWith;
    }
    public Set getCarers() {
        return this.Carers;
    }
    
    public void setCarers(Set Carers) {
        this.Carers = Carers;
    }
    public Set getPatients1() {
        return this.Patients1;
    }
    
    public void setPatients1(Set Patients1) {
        this.Patients1 = Patients1;
    }




}


