package com.aladdin.sc.db;
// Generated Jun 17, 2010 2:46:26 PM by Hibernate Tools 3.2.4.GA


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private Integer id;
     private Integer TaskType;
     private Timestamp DateTimeAssigned;
     private Timestamp DateTimeFulfilled;
     private Integer TaskStatus;
     private String url;
     private Integer questionnaire;
     private Integer Executor;
     private Integer Assigner;
     private Integer Object;
     private Questionnaire m_Questionnairequestionnaire;
     private Users m_UsersExecutor;
     private Users m_UsersAssigner;
     private Users m_UsersObject;
     private Set Measurements = new HashSet(0);

    public Task() {
    }

    public Task(Integer TaskType, Timestamp DateTimeAssigned, Timestamp DateTimeFulfilled, Integer TaskStatus, String url, Integer questionnaire, Integer Executor, Integer Assigner, Integer Object, Questionnaire m_Questionnairequestionnaire, Users m_UsersExecutor, Users m_UsersAssigner, Users m_UsersObject, Set Measurements) {
       this.TaskType = TaskType;
       this.DateTimeAssigned = DateTimeAssigned;
       this.DateTimeFulfilled = DateTimeFulfilled;
       this.TaskStatus = TaskStatus;
       this.url = url;
       this.questionnaire = questionnaire;
       this.Executor = Executor;
       this.Assigner = Assigner;
       this.Object = Object;
       this.m_Questionnairequestionnaire = m_Questionnairequestionnaire;
       this.m_UsersExecutor = m_UsersExecutor;
       this.m_UsersAssigner = m_UsersAssigner;
       this.m_UsersObject = m_UsersObject;
       this.Measurements = Measurements;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getTaskType() {
        return this.TaskType;
    }
    
    public void setTaskType(Integer TaskType) {
        this.TaskType = TaskType;
    }
    public Timestamp getDateTimeAssigned() {
        return this.DateTimeAssigned;
    }
    
    public void setDateTimeAssigned(Timestamp DateTimeAssigned) {
        this.DateTimeAssigned = DateTimeAssigned;
    }
    public Timestamp getDateTimeFulfilled() {
        return this.DateTimeFulfilled;
    }
    
    public void setDateTimeFulfilled(Timestamp DateTimeFulfilled) {
        this.DateTimeFulfilled = DateTimeFulfilled;
    }
    public Integer getTaskStatus() {
        return this.TaskStatus;
    }
    
    public void setTaskStatus(Integer TaskStatus) {
        this.TaskStatus = TaskStatus;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getQuestionnaire() {
        return this.questionnaire;
    }
    
    public void setQuestionnaire(Integer questionnaire) {
        this.questionnaire = questionnaire;
    }
    public Integer getExecutor() {
        return this.Executor;
    }
    
    public void setExecutor(Integer Executor) {
        this.Executor = Executor;
    }
    public Integer getAssigner() {
        return this.Assigner;
    }
    
    public void setAssigner(Integer Assigner) {
        this.Assigner = Assigner;
    }
    public Integer getObject() {
        return this.Object;
    }
    
    public void setObject(Integer Object) {
        this.Object = Object;
    }
    public Questionnaire getM_Questionnairequestionnaire() {
        return this.m_Questionnairequestionnaire;
    }
    
    public void setM_Questionnairequestionnaire(Questionnaire m_Questionnairequestionnaire) {
        this.m_Questionnairequestionnaire = m_Questionnairequestionnaire;
    }
    public Users getM_UsersExecutor() {
        return this.m_UsersExecutor;
    }
    
    public void setM_UsersExecutor(Users m_UsersExecutor) {
        this.m_UsersExecutor = m_UsersExecutor;
    }
    public Users getM_UsersAssigner() {
        return this.m_UsersAssigner;
    }
    
    public void setM_UsersAssigner(Users m_UsersAssigner) {
        this.m_UsersAssigner = m_UsersAssigner;
    }
    public Users getM_UsersObject() {
        return this.m_UsersObject;
    }
    
    public void setM_UsersObject(Users m_UsersObject) {
        this.m_UsersObject = m_UsersObject;
    }
    public Set getMeasurements() {
        return this.Measurements;
    }
    
    public void setMeasurements(Set Measurements) {
        this.Measurements = Measurements;
    }




}


