package com.aladdin.sc.db;
// Generated Jun 17, 2010 2:46:26 PM by Hibernate Tools 3.2.4.GA


import java.sql.Timestamp;

/**
 * Warning generated by hbm2java
 */
public class Warning  implements java.io.Serializable {


     private Integer id;
     private String ID;
     private Integer TypeOfWarning;
     private Timestamp DateTimeOfWarning;
     private Integer Effect;
     private Integer Indicator;
     private Integer RiskLevel;
     private String JustificationText;
     private Integer EmergencyLevel;
     private String PatientID;
     private Boolean Delivered;

    public Warning() {
    }

    public Warning(String ID, Integer TypeOfWarning, Timestamp DateTimeOfWarning, Integer Effect, Integer Indicator, Integer RiskLevel, String JustificationText, Integer EmergencyLevel, String PatientID, Boolean Delivered) {
       this.ID = ID;
       this.TypeOfWarning = TypeOfWarning;
       this.DateTimeOfWarning = DateTimeOfWarning;
       this.Effect = Effect;
       this.Indicator = Indicator;
       this.RiskLevel = RiskLevel;
       this.JustificationText = JustificationText;
       this.EmergencyLevel = EmergencyLevel;
       this.PatientID = PatientID;
       this.Delivered = Delivered;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getID() {
        return this.ID;
    }
    
    public void setID(String ID) {
        this.ID = ID;
    }
    public Integer getTypeOfWarning() {
        return this.TypeOfWarning;
    }
    
    public void setTypeOfWarning(Integer TypeOfWarning) {
        this.TypeOfWarning = TypeOfWarning;
    }
    public Timestamp getDateTimeOfWarning() {
        return this.DateTimeOfWarning;
    }
    
    public void setDateTimeOfWarning(Timestamp DateTimeOfWarning) {
        this.DateTimeOfWarning = DateTimeOfWarning;
    }
    public Integer getEffect() {
        return this.Effect;
    }
    
    public void setEffect(Integer Effect) {
        this.Effect = Effect;
    }
    public Integer getIndicator() {
        return this.Indicator;
    }
    
    public void setIndicator(Integer Indicator) {
        this.Indicator = Indicator;
    }
    public Integer getRiskLevel() {
        return this.RiskLevel;
    }
    
    public void setRiskLevel(Integer RiskLevel) {
        this.RiskLevel = RiskLevel;
    }
    public String getJustificationText() {
        return this.JustificationText;
    }
    
    public void setJustificationText(String JustificationText) {
        this.JustificationText = JustificationText;
    }
    public Integer getEmergencyLevel() {
        return this.EmergencyLevel;
    }
    
    public void setEmergencyLevel(Integer EmergencyLevel) {
        this.EmergencyLevel = EmergencyLevel;
    }
    public String getPatientID() {
        return this.PatientID;
    }
    
    public void setPatientID(String PatientID) {
        this.PatientID = PatientID;
    }
    public Boolean getDelivered() {
        return this.Delivered;
    }
    
    public void setDelivered(Boolean Delivered) {
        this.Delivered = Delivered;
    }




}


