//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.11 at 11:39:38 AM CEST 
//


package com.aladdin.xsd.iface;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuestionnaireQuestionAnswerType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QuestionnaireQuestionAnswerType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OneAnswer"/>
 *     &lt;enumeration value="ManyAnswers"/>
 *     &lt;enumeration value="FreeText"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QuestionnaireQuestionAnswerType")
@XmlEnum
public enum QuestionnaireQuestionAnswerType {

    @XmlEnumValue("OneAnswer")
    ONE_ANSWER("OneAnswer"),
    @XmlEnumValue("ManyAnswers")
    MANY_ANSWERS("ManyAnswers"),
    @XmlEnumValue("FreeText")
    FREE_TEXT("FreeText");
    private final String value;

    QuestionnaireQuestionAnswerType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QuestionnaireQuestionAnswerType fromValue(String v) {
        for (QuestionnaireQuestionAnswerType c: QuestionnaireQuestionAnswerType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
