create table Address (id integer not null, Street varchar(255), StreetNo varchar(255), City varchar(255), County varchar(255), Country varchar(255), ZipCode varchar(255), Notes varchar(255), IsPrimary bit, persondata integer, primary key (id));
create table Administrator (id integer not null, personData integer, primary key (id));
create table AladdinUser (id integer not null, username varchar(255), password varchar(255), type integer, personId integer, primary key (id));
create table Carer (id integer not null, persondata integer, sd integer, primary key (id));
create table CarerAssessment (id integer not null, carer integer, DateOfAssessment timestamp, RelevantHealthProblem varchar(255), SeverityOfBurden integer, EmotionalOrMentalDisorder varchar(255), PsychoactiveDrugs varchar(255), QualityOfLife integer, clinician integer, primary key (id));
create table Clinician (id integer not null, persondata integer, primary key (id));
create table Communication (id integer not null, Type varchar(255), Value varchar(255), Notes varchar(255), IsPrimary bit, persondata integer, primary key (id));
create table Dict (id integer not null, code varchar(255), description varchar(255), locale integer, type integer, primary key (id));
create table EntertainmentContent (id integer not null, title varchar(255), url varchar(255), type varchar(255), category varchar(255), text varchar(255), enabled bit, primary key (id));
create table ExternalService (id integer not null, Address varchar(255), Description varchar(255), Type varchar(255), primary key (id));
create table Identifier (id integer not null, Type varchar(255), Number varchar(255), IssueDate timestamp, IssueAuthority varchar(255), persondata integer, primary key (id));
create table Locale (id integer not null, name varchar(255), primary key (id));
create table Measurement (id integer not null, type varchar(255), value numeric, datetime timestamp, units varchar(255), lowerlimit numeric, upperlimit numeric, patientassessment integer, task integer, primary key (id));
create table Patient (id integer not null, persondata integer, sd integer, clinician integer, swname varchar(255), swphone varchar(255), swemail varchar(255), ccname varchar(255), ccphone varchar(255), ccemail varchar(255), gpname varchar(255), gpphone varchar(255), gpemail varchar(255), carer integer, primary key (id));
create table PatientAssessment (id integer not null, patient integer, DateOfAssessment timestamp, Aetology integer, TimeElapsedSinceDiagnose integer, Severity integer, RelevantPathologyAntecedents varchar(255), Comorbidity varchar(255), CharlsonComobodityIndex integer, BarthelIndex integer, LawtonIndex integer, MMSE integer, MDRS integer, BlessedScalePart1 numeric, BlessedScalePart2 integer, BlessedScalePart3 integer, ChecklistMBPC integer, NPQISeverity integer, NPQIStress integer, GDS integer, Falls bit, Incontinence bit, Delirium bit, Immobility bit, SensorialDeficits bit, PharmacologyTreatment varchar(255), primary key (id));
create table PersonData (id integer not null, Surname varchar(255), Name varchar(255), primary key (id));
create table Questionnaire (id integer not null, version numeric, title varchar(255), primary key (id));
create table QuestionnaireAnswer (id integer not null, question integer, value varchar(255), UserId integer, timestamp timestamp, objectId integer, primary key (id));
create table QuestionnaireQuestion (id integer not null, type varchar(255), isPrimary bit, parentid integer, title varchar(255), quest integer, condition integer, deleted bit, "position" integer, GlobalId integer, primary key (id));
create table QuestionnaireQuestionAnswer (id integer not null, value integer, description varchar(255), question integer, deleted bit, "position" integer, primary key (id));
create table SocioDemographicData (id integer not null, Gender integer, MaritalStatus integer, Children integer, LivingWith integer, birthday timestamp, primary key (id));
create table SystemParameter (id integer not null, Code varchar(255), Description varchar(255), primary key (id));
create table Task (id integer not null, TaskType integer, DateTimeAssigned timestamp, DateTimeFulfilled timestamp, TaskStatus integer, url varchar(255), text varchar(255), questionnaire integer, Executor integer, Assigner integer, Object integer, primary key (id));
create table Translate (id integer not null, entityid integer, entity varchar(255), locale integer, value varchar(255), primary key (id));
create table Warning (id integer not null, TypeOfWarning integer, DateTimeOfWarning timestamp, Effect integer, Indicator integer, RiskLevel integer, JustificationText varchar(255), EmergencyLevel integer, Delivered bit, Patient integer, primary key (id));
alter table Address add constraint FK1ED033D44EAC96B0 foreign key (persondata) references PersonData;
alter table Administrator add constraint FK8BEF2AD4EAC96B0 foreign key (personData) references PersonData;
alter table Carer add constraint FK3DDF7614EAC96B0 foreign key (persondata) references PersonData;
alter table Carer add constraint FK3DDF761B1CF35A5 foreign key (sd) references SocioDemographicData;
alter table CarerAssessment add constraint FK9BE20503513C2A30 foreign key (carer) references Carer;
alter table CarerAssessment add constraint FK9BE20503F8FC050A foreign key (clinician) references Clinician;
alter table Clinician add constraint FK1501984E4EAC96B0 foreign key (persondata) references PersonData;
alter table Communication add constraint FKF1E9FFB64EAC96B0 foreign key (persondata) references PersonData;
alter table Dict add constraint FK207FD6F67D2746 foreign key (locale) references Locale;
alter table Identifier add constraint FK165A88C94EAC96B0 foreign key (persondata) references PersonData;
alter table Measurement add constraint FKF75C839C5542F21C foreign key (task) references Task;
alter table Measurement add constraint FKF75C839CFC90A15C foreign key (patientassessment) references PatientAssessment;
alter table Patient add constraint FK340C82E5513C2A30 foreign key (carer) references Carer;
alter table Patient add constraint FK340C82E54EAC96B0 foreign key (persondata) references PersonData;
alter table Patient add constraint FK340C82E5F8FC050A foreign key (clinician) references Clinician;
alter table Patient add constraint FK340C82E5B1CF35A5 foreign key (sd) references SocioDemographicData;
alter table PatientAssessment add constraint FKDD8AFB8752781DB8 foreign key (patient) references Patient;
alter table QuestionnaireAnswer add constraint FK161DFB211EDFD5BD foreign key (question) references QuestionnaireQuestion;
alter table QuestionnaireQuestion add constraint FKDED4AA896D8B73B3 foreign key (quest) references Questionnaire;
alter table QuestionnaireQuestion add constraint FKDED4AA89AA692D1C foreign key (parentid) references QuestionnaireQuestion;
alter table QuestionnaireQuestionAnswer add constraint FK17920BA71EDFD5BD foreign key (question) references QuestionnaireQuestion;
alter table Task add constraint FK27A9A52A7D6874 foreign key (questionnaire) references Questionnaire;
alter table Task add constraint FK27A9A5D3883C27 foreign key (Executor) references AladdinUser;
alter table Task add constraint FK27A9A543B65130 foreign key (Assigner) references AladdinUser;
alter table Task add constraint FK27A9A51CC2E693 foreign key (Object) references AladdinUser;
alter table Translate add constraint FKB633112EF67D2746 foreign key (locale) references Locale;
alter table Warning add constraint FKA63E477C52781DB8 foreign key (Patient) references Patient;
create sequence Address_id_seq;
create sequence Administrator_id_seq;
create sequence AladdinUser_id_seq;
create sequence CarerAssessment_id_seq;
create sequence Carer_id_seq;
create sequence Clinician_id_seq;
create sequence Communication_id_seq;
create sequence Dict_id_seq;
create sequence EntertainmentContent_id_seq;
create sequence ExternalService_id_seq;
create sequence Identifier_id_seq;
create sequence Locale_id_seq;
create sequence Measurement_id_seq;
create sequence PatientAssessment_id_seq;
create sequence Patient_id_seq;
create sequence PersonData_id_seq;
create sequence QuestionnaireAnswer_id_seq;
create sequence QuestionnaireQuestionAnswer_id_seq;
create sequence QuestionnaireQuestion_id_seq;
create sequence Questionnaire_id_seq;
create sequence SocioDemographicData_id_seq;
create sequence SystemParameter_id_seq;
create sequence Task_id_seq;
create sequence Translate_id_seq;
create sequence Warning_id_seq;
